### PR TITLE
Add Name and Application for Spinnaker pipeline types

### PR DESCRIPTION
**Pull request by bobbytables**
Adds the application name to the `SpinnakerPipeline` type so we can post this to the Spinnaker API to update pipelines automatically.

### CODE REVIEW

**Comment by shraykay** [comment]
thought we had these o_o

**Comment by bobbytables** [comment]
> thought we had these o_o

Different struct.

**Comment by mhamrah** [comment]
You can't update with I'd?!?!

**Comment by bobbytables** [comment]
Nope, it's garbage. It's a `POST /pipelines` and the JSON needs to include all of the detail.

**Pull request merged**
